#!/bin/bash

#---------------- Folder Arrangement ------------#
#                  |- train                      #
#         |- Data -|- test                       #
# ~/home -|- Packages                            #
#         |- Output -|- train                    #
#                    |- test                     #
#------------------------------------------------#


root_path='/home/elec5622'
data_root=$root_path'/Data/'
package_DIR=$root_path'/Packages/'

output_path=$root_path'/Output/'
train_output_path=$root_path'/Output/train/'
test_output_path=$root_path'/Output/test/'
floImg=$package_DIR'MNI152_T1_1mm_brain.nii'
aalImg=$package_DIR'aal.nii'

#====================  measurement =======================#
echo "=============== begin measurement... ========"

#----- processing training images
cd $data_root'train/'
subIDs=`ls`

for subID in $subIDs 
do
	echo "Processing training image "$subID
     fileext='.nii.gz'
     file=$subID
     basename $file $fileext
     filename="${file%%.*}"
 

  
     subGMMask=$train_output_path$filename'_greymatter_mask.nii.gz'

     echo " >>>> Create measurements for "$filename"  <<<<<<"
     source ${root_path}/CreateSeedMask $train_output_path 'AAL_to_'$filename$fileext 
	echo "i am done!"
     seedMask_path=$train_output_path'seedMasks/'
 	cd $seedMask_path
	mask_IMGs=`ls | wc -l`	
            
     echo -n $filename >> ${train_output_path}"AAL_statistics_volumn_train.csv"

	for i in $(eval echo {1..$mask_IMGs}); 
	do
	        #echo "i: "${i}
          	#Calculate volume and save it into csv file
 		#TODO
                    #for general regional volumes
            fslstats MRI_example_brain.nii.gz -k transformed_Temporal_Mid_L_mask.nii.gz -V
            fslstats MRI_example_brain.nii.gz -k transformed_Temporal_Mid_R_mask.nii.gz -V

            #for specifically greymatter volumes
            fslmaths transformed_Temporal_Mid_L_mask.nii.gz -mul MRI_example_greymatter_mask.nii.gz MRI_example_greymatter_Temp_L_mask.nii.gz
            fslmaths transformed_Temporal_Mid_R_mask.nii.gz -mul MRI_example_greymatter_mask.nii.gz MRI_example_greymatter_Temp_R_mask.nii.gz

            fslstats MRI_example_brain.nii.gz -k MRI_example_greymatter_Temp_L_mask.nii.gz -V
            fslstats MRI_example_brain.nii.gz -k MRI_example_greymatter_Temp_R_mask.nii.gz -V
     	done
	
	#TODO

    	rm '-rf' $seedMask_path   
     	cd $data_root'train/'

done

#----- processing test images
cd $data_root'test/'
subIDs=`ls`

for subID in $subIDs 
do
	echo "Processing test image "$subID
     fileext='.nii.gz'
     file=$subID
     basename $file $fileext
     filename="${file%%.*}"

     subGMMask=$test_output_path$filename'_greymatter_mask.nii.gz'

     echo " >>>> Create measurements for "$filename"  <<<<<<"
     source ${root_path}/CreateSeedMask $test_output_path 'AAL_to_'$filename$fileext 

     seedMask_path=$test_output_path'seedMasks/'
 	cd $seedMask_path
	mask_IMGs=`ls | wc -l`	
            
     echo -n $filename >> ${test_output_path}"AAL_statistics_volumn_test.csv"

	for i in $(eval echo {1..$mask_IMGs}); 
	do
          	#echo "i: "${i}
          	#Calculate volume and save it into csv file
          	#TODO
            #for general regional volumes
            fslstats MRI_example_brain.nii.gz -k transformed_Temporal_Mid_L_mask.nii.gz -V
            fslstats MRI_example_brain.nii.gz -k transformed_Temporal_Mid_R_mask.nii.gz -V

            #for specifically greymatter volumes
            fslmaths transformed_Temporal_Mid_L_mask.nii.gz -mul MRI_example_greymatter_mask.nii.gz MRI_example_greymatter_Temp_L_mask.nii.gz
            fslmaths transformed_Temporal_Mid_R_mask.nii.gz -mul MRI_example_greymatter_mask.nii.gz MRI_example_greymatter_Temp_R_mask.nii.gz

            fslstats MRI_example_brain.nii.gz -k MRI_example_greymatter_Temp_L_mask.nii.gz -V
            fslstats MRI_example_brain.nii.gz -k MRI_example_greymatter_Temp_R_mask.nii.gz -V
     	done
	#TODO


     rm '-rf' $seedMask_path   
     cd $data_root'test/'
         
done


#==================== End of measurement  =========#
