#!/bin/bash

#---------------- Folder Arrangement ------------#
#                  |- train                      #
#         |- Data -|- test                       #
# ~/home -|- Packages                            #
#         |- Output -|- train                    #
#                    |- test                     #
#------------------------------------------------#


root_path=${PWD}
data_root=$root_path'/Data/'
package_DIR=$root_path'/Packages/'

output_path=$root_path'/Output/'
train_output_path=$root_path'/Output/train/'
test_output_path=$root_path'/Output/test/'
floImg=$package_DIR'MNI152_T1_1mm_brain.nii'
aalImg=$package_DIR'aal.nii'
ROI_no=90

#====================  measurement =======================#
echo "=============== begin measurement... ========"

#----- processing training images
cd $output_path'train/'
subIDs=$(ls | grep ".*_stripped_greymatter_mask.nii.gz")
if [[ ! -f "AAL_statistics_volumn_train.csv" ]]
then
for subID in $subIDs 
do
	echo "Processing training image "$subID
     gmmask=$subID
     basename=$( echo $gmmask | sed 's/_stripped_greymatter_mask.nii.gz//' )
     echo $basename
     aalmask="aal_to_"$basename"_stripped_transformed.nii.gz"
     echo $aalmask
            
     echo -n $basename >> ${train_output_path}"AAL_statistics_volumn_train.csv"

	for i in $(eval echo {1..$ROI_no}); 
	do
	     echo "i: "${i}

		fslmaths $aalmask -thr $i -uthr $i -bin $basename"_"$i"_aalROImask.nii.gz"
		output=$( fslstats $gmmask -k $basename"_"$i"_aalROImask.nii.gz" -V )
          for item in $output;
          do
               echo -n ", "$item >> ${train_output_path}"AAL_statistics_volumn_train.csv"
          done
		#where will this put the voxel vs not voxel items?
          rm $basename"_"$i"_aalROImask.nii.gz"
	done
	
	echo "" >> ${train_output_path}"AAL_statistics_volumn_train.csv"
	#this will end the column

done
fi
#----- processing test images
cd $output_path'test/'
subIDs=$(ls | grep ".*_stripped_greymatter_mask.nii.gz")
if [[ ! -f "AAL_statistics_volumn_test.csv" ]]
then
for subID in $subIDs 
do
	echo "Processing testing image "$subID
     gmmask=$subID
     basename=$( echo $gmmask | sed 's/_stripped_greymatter_mask.nii.gz//' )
     echo $basename
     aalmask="aal_to_"$basename"_stripped_transformed.nii.gz"
     echo $aalmask
            
     echo -n $basename >> ${test_output_path}"AAL_statistics_volumn_test.csv"

	for i in $(eval echo {1..$ROI_no}); 
	do
	     echo "i: "${i}

		fslmaths $aalmask -thr $i -uthr $i -bin $basename"_"$i"_aalROImask.nii.gz"
		output=$( fslstats $gmmask -k $basename"_"$i"_aalROImask.nii.gz" -V )
          for item in $output;
          do
               echo -n ", "$item >> ${test_output_path}"AAL_statistics_volumn_test.csv"
          done
		#where will this put the voxel vs not voxel items?
          rm $basename"_"$i"_aalROImask.nii.gz"
	done
	
	echo "" >> ${test_output_path}"AAL_statistics_volumn_test.csv"
	#this will end the column
done
fi

#==================== End of measurement  =========#
