#!/bin/bash


#---------------- Folder Arrangement ------------#
#                  |- train                      #
#         |- Data -|- test                       #
# ~/home -|- Packages                            #
#         |- Output -|- train                    #
#                    |- test                     #
#------------------------------------------------#


root_path='/home/elec5622'
data_root=$root_path'/Data/'
package_DIR=$root_path'/Packages/'

output_path=$root_path'/Output/'
train_output_path=$root_path'/Output/train/'
test_output_path=$root_path'/Output/test/'

#================== Grey matter segmentation ==========#
echo "=============== begin grey matter segmentation...========"

#----- processing training images
cd $data_root'train/'
subIDs=$(ls | grep ".*-stripped.nii.gz")

for subID in $subIDs 
do
	echo "Processing training image "$subID
     	fileext='.nii.gz'
     	file=$subID
    	basename $file $fileext
     	filename="${file%%.*}"

     	#tissue segmentation
     	base=$train_output_path$filename
     	#TODO
        fast -S 1 -n 3 -t 1 -g -v -o MRI_example_brain $filename.nii.gz
        mv MRI_example_brain_seg_0.nii.gz MRI_example_csf_mask.nii.gz
        mv MRI_example_brain_seg_1.nii.gz MRI_example_greymatter_mask.nii.gz
        mv MRI_example_brain_seg_2.nii.gz MRI_example_whitematter_mask.nii.gz
        rm MRI_example_brain_pve*

        #and if we for some reason need original data from the greymatter regions
        fslmaths MRI_example_greymatter_mask.nii.gz -mul MRI_example.nii.gz MRI_example_brain_greymatter.nii.gz
     	done


#---- processing test images
cd $data_root'test/'
subIDs=`ls`

for subID in $subIDs 
do
echo "Processing test image "$subID

     	fileext='.nii.gz'
     	file=$subID
     	basename $file $fileext
     	filename=$file
     	filename="${file%%.*}"

     	#tissue segmentation
     	base=$test_output_path$filename
     	#TODO
        fast -S 1 -n 3 -t 1 -g -v -o MRI_example_brain MRI_example_brain.nii.gz
        mv MRI_example_brain_seg_0.nii.gz MRI_example_csf_mask.nii.gz
        mv MRI_example_brain_seg_1.nii.gz MRI_example_greymatter_mask.nii.gz
        mv MRI_example_brain_seg_2.nii.gz MRI_example_whitematter_mask.nii.gz
        rm MRI_example_brain_pve*

        #and if we for some reason need original data from the greymatter regions
        fslmaths MRI_example_greymatter_mask.nii.gz -mul MRI_example.nii.gz MRI_example_brain_greymatter.nii.gz
        
done

#Please carefully check the segmented grey matter mask visually using fsleyes to ensure the result is correct.#
#============= End of Grey matter segmentation=================#
